package:
  name: "libadwaita"
  version: "1.6.9"
  type: "binary"
  architecture: "x86_64"
  description: "Building blocks for modern GNOME applications"
  maintainer: "APGer <anmitali198@gmail.com>"
  license: "LGPL-2.1"
  homepage: "https://gitlab.gnome.org/GNOME/libadwaita"
  tags: ["gnome", "gtk4", "library", "ui", "adwaita"]
  dependencies: ["gtk4", "glib", "fribidi", "pango", "cairo"]
  conflicts: []
  provides: []
  replaces: []
  conf: []

source:
  url: "https://gitlab.gnome.org/GNOME/libadwaita/-/archive/{{VERSION}}/libadwaita-{{VERSION}}.tar.gz"

build:
  dependencies: 
    - "meson"
    - "ninja-build"
    - "pkg-config"
    - "libgtk-4-dev"
    - "libglib2.0-dev"
    - "libfribidi-dev"
    - "libpango1.0-dev"
    - "libcairo2-dev"
    - "gobject-introspection"
    - "libgirepository1.0-dev"
  script: |
    meson setup _build \
      -Dprefix=/usr \
      -Dtests=false \
      -Dexamples=false \
      -Dintrospection=enabled \
      -Dvapi=false
    ninja -C _build

install:
  script: "ninja -C _build install"
