package:
  name: "libadwaita"
  version: "1.6.9"
  type: "binary"
  architecture: "x86_64"
  description: "Building blocks for modern GNOME applications"
  maintainer: "APGer <anmitali198@gmail.com>"
  license: "LGPL-2.1"
  homepage: "https://gitlab.gnome.org/GNOME/libadwaita"
  tags: ["gnome", "gtk4", "library", "ui", "adwaita"]
  dependencies: ["gtk4", "glib", "fribidi", "pango", "cairo"]
  conflicts: []
  provides: []
  replaces: []
  conf: []

source:
  url: "https://gitlab.gnome.org/GNOME/libadwaita/-/archive/{{VERSION}}/libadwaita-{{VERSION}}.tar.gz"

build:
  dependencies: 
    - "python3-pip"
    - "ninja-build" 
    - "pkg-config"
    - "libgtk-4-dev"
    - "libglib2.0-dev"
    - "libfribidi-dev"
    - "libpango1.0-dev"
    - "libcairo2-dev"
    - "gobject-introspection"
    - "libgirepository1.0-dev"
    - "meson"  
  script: |
    export PATH=/usr/bin:$PATH
    which meson
    meson --version
    
    GLIB_VERSION=$(pkg-config --modversion glib-2.0)
    if dpkg --compare-versions "$GLIB_VERSION" lt "2.84"; then
      echo "Building glib 2.84..."
      cd /tmp
      wget https://download.gnome.org/sources/glib/2.84/glib-2.84.0.tar.xz
      tar -xf glib-2.84.0.tar.xz
      cd glib-2.84.0
      meson setup _build --prefix=/usr -Dtests=false
      ninja -C _build
      sudo ninja -C _build install
      sudo ldconfig
      cd -
    fi
    
    meson setup _build \
      -Dprefix=/usr \
      -Dtests=false \
      -Dexamples=false \
      -Dintrospection=enabled \
      -Dvapi=false
    ninja -C _build
