package:
  name: "libadwaita"
  version: "1.6.9"
  type: "binary"
  architecture: "x86_64"
  description: "Building blocks for modern GNOME applications"
  maintainer: "APGer <anmitali198@gmail.com>"
  license: "LGPL-2.1"
  homepage: "https://gitlab.gnome.org/GNOME/libadwaita"
  tags: ["gnome", "gtk4", "library", "ui", "adwaita"]
  dependencies: ["gtk4", "glib", "fribidi", "pango", "cairo"]
  conflicts: []
  provides: []
  replaces: []
  conf: []

source:
  url: "https://gitlab.gnome.org/GNOME/libadwaita/-/archive/{{VERSION}}/libadwaita-{{VERSION}}.tar.gz"

build:
  script: |
    cd /tmp
    wget https://download.gnome.org/sources/glib/2.84/glib-2.84.0.tar.xz
    tar -xf glib-2.84.0.tar.xz
    cd glib-2.84.0
    pip3 install meson --break-system-packages
    meson setup _build --prefix=/usr
    ninja -C _build
    sudo ninja -C _build install
    
    # libadwaita
    cd $BUILD_DIR
    meson setup _build \
      -Dprefix=/usr \
      -Dtests=false \
      -Dexamples=false \
      -Dintrospection=enabled \
      -Dvapi=false
    ninja -C _build
    
install:
  script: "ninja -C _build install"
