# APGer Recipe Template for NurOS Packages
# Edit this file to define your package build configuration

package:
  name: "package-name"           # Package name (required)
  version: "1.0.0"               # Package version (required)
  type: "binary"                 # Type: binary, meta, library (required)
  architecture: "x86_64"         # Architecture: x86_64, aarch64, any (required)
  description: "Package description" # Short description (required)
  maintainer: "Your Name <email@example.com>" # Maintainer info (required)
  license: "GPL-3.0"             # License identifier (required)
  homepage: "https://example.com" # Project homepage (optional)
  tags: ["tag1", "tag2"]         # Tags for categorization (optional)
  dependencies: []               # Runtime dependencies (optional)
  conflicts: []                  # Conflicting packages (optional)
  provides: []                   # Virtual packages provided (optional)
  replaces: []                   # Packages replaced by this one (optional)
  conf: []                       # Configuration files paths (optional)

source:
  url: "https://example.com/source.tar.xz" # Source archive URL (required)

build:
  script: "./configure --prefix=/usr && make" # Build commands (required)

install:
  script: "make DESTDIR=\"$DESTDIR\" install" # Install commands to $DESTDIR (required)
